### ISSUE TITLE
Testing Locally

### ISSUE THREAD

**Issue by jletey** [nikitavoloboev/markdown-parser#12]
How exactly should I test to see if my edited code works? I see that you have a `parser_test.go` file, but I can't seem to test it without getting an error (`go test parser_test.go`):

```
# command-line-arguments [command-line-arguments.test]
./parser_test.go:9:6: missing function body
./parser_test.go:10:6: missing function body
./parser_test.go:11:6: missing function body
./parser_test.go:15:2: undefined: ParseLinkWithDescription
./parser_test.go:20:17: undefined: ParseMarkdownFile
FAIL	command-line-arguments [build failed]
```

Note that I do have my fork cloned into `~/go/src/johnletey/markdown-parser`

**Comment by nikivdev** [comment]
This test has to be redone completely. I was learning Go back then.

If you have this in the test file:

```go
package parser

import (
	"fmt"
	"testing"
)

// func TestParseLinkWithDescription(t *testing.T) {
// 	v := "- [Effective Go](https://golang.org/doc/effective_go.html) - Amazing doc."
// 	ParseLinkWithDescription(v)
// 	// result := TestParseLinkWithDescription(v)
// }

func TestParseMarkdownFile(t *testing.T) {
	// result, err := ParseMarkdownFile("websites.md")
	// if err != nil {
	// 	log.Fatal(err)
	// }
	fmt.Println("test")
}
```

The test will pass when you run `go test`. We should add the test when we write the code for it. What's currently there maybe used for inspiration for a proper test(s).

**Comment by jletey** [comment]
I see ... thanks for the help!

**Comment by nikivdev** [comment]
https://golang.org/pkg/testing/ is a good place to start
